{% set name = "acstools" %}
{% set version = "3.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8bae89f2747693f2f58e792810290695d905c415fe8ce0a4df5c41a13e425fe0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - acs_destripe = acstools.acs_destripe:main
    - acs_destripe_plus = acstools.acs_destripe_plus:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base
    - requests
    - pyyaml
    - scipy
    - scikit-image
    - photutils

test:
  requires:
    - python {{ python_min }}
  imports:
    - acstools
  commands:
    - acs_destripe --help
    - acs_destripe_plus --help

about:
  home: https://github.com/spacetelescope/acstools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python Tools for HST ACS
  description: Python Tools for HST ACS (Advanced Camera for Surveys) Data
  doc_url: https://acstools.readthedocs.io/
  dev_url: https://github.com/spacetelescope/acstools

extra:
  recipe-maintainers:
    - pllim
    - jryon
    - rjavila
