{% set name = "acstools" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d609715c2c3a155fa53be8b8762b8d7978437ee5bbdef1e35e1af30da278b528

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - acs_destripe = acstools.acs_destripe:main
    - acs_destripe_plus = acstools.acs_destripe_plus:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy
    - astropy
    - beautifulsoup4
    - requests
    - pyyaml
    - scipy
    - scikit-image
    - photutils

test:
  imports:
    - acstools
  commands:
    - acs_destripe --help
    - acs_destripe_plus --help

about:
  home: https://github.com/spacetelescope/acstools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python Tools for HST ACS
  description: Python Tools for HST ACS (Advanced Camera for Surveys) Data
  doc_url: https://acstools.readthedocs.io/
  dev_url: https://github.com/spacetelescope/acstools

extra:
  recipe-maintainers:
    - pllim
    - jryon
    - rjavila
